### ISSUE TITLE
Thunk Middleware

### ISSUE THREAD

**Issue by primozs** [reduxjs/redux-starter-kit#113]
Its not possible to configure default thunk middleware and if you go with your one you need to install thunk dependency again. Maybe I am missing something.
Cheers

**Comment by markerikson** [comment]
It's not clear what problem you're describing.  Can you clarify?

**Comment by denisw** [comment]
I think the problem is that you cannot configure the thunk middleware with an extra argument (`thunk.withExtraArgument`) without passing a custom `middleware` array, and if you do so, it‘s difficult to keep the other default middleware because `getDefaultMiddleware` already includes the (unconfigured) thunk middleware.

**Comment by markerikson** [comment]
That's kind of the point.  If you want the defaults, use the defaults.  If you want to customize the middleware, customize it yourself.  It's not like it's _that_ complicated - `getDefaultMiddleware()` is only a few lines.

`redux-thunk` is already a dependency, you can just import it yourself instead of relying on `getDefaultMiddleware().

**Comment by primozs** [comment]
Hey,
Yes, its true! Sorry for the noize.
Cheers!
