### ISSUE TITLE
react not re-rendering after updating state that inclueds an `id` key

### ISSUE THREAD

**Issue by BrooksPatton** [reduxjs/redux-starter-kit#143]
I created a todo app using Redux Starter Kit with a store that looked like:

```javascript
const initialTodoState = {
    tasks: [
        {
            id: 1,
            name: 'Task name',
            completed: false
        },
        {
            id: 2,
            name: 'Grocery shopping',
            completed: false
        }
    ],
    lastIdToAdd: 2
};
```

When I created an action and reducer to edit the name of a task the store updated in Redux (I was able to see the change in the Redux tools), and console.logging the state showed that Immer has successfully applied the changes. However the React re-render functions didn't get called.

Here is the reducer that I wanted to write

```javascript
function editTaskNameReducer(state, action) {
    const task = state.tasks.find(task => task.id === action.payload.id);

    task.name = action.payload.name;
}
```

I found however that if I changed the id in the task object then everything worked the way that I wanted. The components re-rendered and the app worked as expected. The current reducer logic is

```javascript
function editTaskNameReducer(state, action) {
    const task = state.tasks.find(task => task.id === action.payload.id);

    task.id = state.lastIdToAdd + 1;
    task.name = action.payload.name;
    state.lastIdToAdd += 1;
}
```

Is this a bug or or am I doing something wrong with the reducer?

**Comment by markerikson** [comment]
Hmm. Seems okay at first glance. Can you link to a CodeSandbox or project repo that demonstrates the issue?

**Comment by BrooksPatton** [comment]
absolutely, reducer in question can be found at https://github.com/BrooksPatton/web_dev_rehabilitation/blob/master/micro_projects/front_end/state_management/redux_state/src/store/store.js lines 37 and 55.

**Comment by BrooksPatton** [comment]
I also created a video showing what the problem looks like from my side. Its unlisted on YouTube at https://youtu.be/xB_bIZLAmdQ

**Comment by markerikson** [comment]
Aha.  I think the problem is that you are copying props to state, and displaying the current state value.  Just change `renderTaskName()` to be `this.props.task.name` instead of `this.state.task.name`.

This is a good example of why [copying props to state is discouraged](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html).

I went ahead and created a CodeSandbox that fixes the rendering issue, and also shows how to use `createSlice()` to simplify that reducer some more (including not needing to use that `lastIdToAdd` field any more):

https://codesandbox.io/s/reactstate-cbqum

**Comment by BrooksPatton** [comment]
Awesome, thanks @markerikson !
