### ISSUE TITLE
Suggestion: Include docs on integrating with React

### ISSUE THREAD

**Issue by TidyIQ** [reduxjs/redux-starter-kit#155]
I see that the Provider component (or any react-redux components) isn't included in this package so if you're using React then you'll need to also install `react-redux` manually to get it to work. I'm new to Redux (have previously been using react hooks and context to manage state) so I'm not too sure what other considerations and adjustments need to be made to RSK to get it to play nicely with React. 

Since this is a starter kit I think it would be beneficial to include some documentation on integrating with React for the people like myself who are new to Redux and looking to get set up as painlessly as possible.

**Comment by markerikson** [comment]
Yes, RSK is just about the "plain Redux" aspect, and has nothing to do with React or React-Redux.  You could use RSK to write Redux code that works with React, Angular, Vue, Ember, or vanilla JS, because Redux itself works with any UI layer.

Because of that, there's nothing RSK-specific about using Redux with React, so please see [the normal React-Redux docs](https://react-redux.js.org/) for instructions on using Redux and React together.

There are a bunch of open issues about adding some example apps and tutorials.  I have put together [a small "Github Issues" example app](https://github.com/markerikson/rsk-github-issues-experiment) that I intend to turn into a tutorial in the near future.
