### ISSUE TITLE
How do you mutate the state returned from createReducer?

### ISSUE THREAD

**Issue by rodelrebucas** [reduxjs/redux-starter-kit#159]
If I have an object like this:

```
state = {
loading: false
}
```
and reducer:

```
(state, action) => {
   state.loading = false
}
```

It returns 
> Attempted to assign to readonly property.

Is the state a draft state?

Why can't I change the state like the code above?

**Comment by markerikson** [comment]
Can you show a larger code example of what you're trying to do, preferably as a runnable CodeSandbox?

Also, are you using TypeScript?  If so, what is the declaration for your state structure?

**Comment by rodelrebucas** [comment]
Environment:
 ```
"react-redux": "^7.1.0",
 "redux": "^4.0.1",
"redux-starter-kit": "^0.5.1",
```

I'm using flow and using redux-starter-kit on expo 

Sample Code:

```
export type State = {
  loading: boolean
};
```
```
const initialState: State = {
  loading: false,
};
```
```
export const loginStartedHandler = (state: State) => {
  state.loading = true;
};
```
`export const loginStarted = createAction('LOGIN_STARTED');`
```
const authReducer = createReducer(initialState, {
  [loginStarted]: loginStartedHandler
}
```

Returning a new state like this works:

```
export const loginStartedHandler = (state: State) => {
  return {...state, loading: true}
};
```

But not this: `state.loading = true;`

Why?

**Comment by markerikson** [comment]
Can you clarify what the source of that error message is?  Is it coming from Flow, or is it a runtime error?

**Comment by rodelrebucas** [comment]
The error shows whenever I dispatched `loginStarted`.

**Comment by markerikson** [comment]
It would really help if you could try to reproduce the issue in a CodeSandbox project, and link that here.  Without seeing what's happening myself, I don't think there's much I can do to debug this.

**Comment by rodelrebucas** [comment]
Hi please check this snack: https://snack.expo.io/rJcLo-hWB

**Comment by markerikson** [comment]
Aha.  Yes, I see the problem now:

![image](https://user-images.githubusercontent.com/1128784/61343811-216fbe00-a81d-11e9-9209-86e9f93f8621.png)

Your example has this line:

```js
export const loginStartedHandler = (state, action) =>  state.loading = true;
```

Notice that this line does two things:

- It mutates `state.loading`
- The arrow function implicitly returns the result of that expression.

Immer lets you provide an update in two ways:

- You can mutate the draft state object
- You can return a new value

But, you can't do _both_, and that's what's happening here.

We do warn about this [at the bottom of the `createReducer()` docs page](https://redux-starter-kit.js.org/api/createreducer#direct-state-mutation) (which links to [the Immer docs on this issue]()https://github.com/immerjs/immer#pitfalls), but it's probably not as clear as it should be.

There's a couple ways to fix this.  One is to [put the `void` keyword in front of the statement](https://github.com/immerjs/immer#inline-shortcuts-using-void).  Another is to use curly braces to form a function body instead of an implicit return.

Also, as a side note: you can use our [`createSlice()` function](https://redux-starter-kit.js.org/api/createSlice) to simplify even that little bit of logic you have in `store.js`:

```js
const initialState = {
  loading: false,
};

const authSlice = createSlice({
    slice : "auth",
    initialState,
    reducers: {
        loginStarted(state, action) {
            state.loading = true;
        }
    }
});
```

**Comment by rodelrebucas** [comment]
Thank you so much. Should have read more on Immer docs.
