### ISSUE TITLE
Typescript errors when passing null as payload to actions returned from createSlice

### ISSUE THREAD

**Issue by marko911** [reduxjs/redux-starter-kit#165]
When using actions created from `createSlice`, Typescript complains with: 

`Argument of type 'null' is not assignable to parameter of type '{}'` .
But if you just use actions from `createAction` , it compiles. 

[Sandbox example](https://codesandbox.io/embed/black-firefly-uhweh)

**Comment by markerikson** [comment]
tagging @phryneas @Dudeonyx @denisw @jessidhia

**Comment by phryneas** [comment]
Okay, this seems to come from the fact that you are using TS 3.3 - in TS 3.5, the action type infers to a `PayloadActionCreator<unknown, string, void>` which in fact accepts `null`. Older versions of TS default to `{}` instead of `unknown`.

I'll try and see if we can have it default to `unknown` in older TS versions. But adding a test for this will be impossible if we don't want to downgrade TS for all tests (although it might be a good idea to run the tests in different TS versions in a separate ticket - what do you think @markerikson ?)

**Comment by phryneas** [comment]
see #166 - could you please test this?

**Comment by marko911** [comment]
Ok I updated my TS versio from 3.4 to 3.5.3 and it solves the problem yes.

**Comment by markerikson** [comment]
Hopefully resolved by #166 .  Merged, and will probably get that change out in 0.8 .
