### ISSUE TITLE
Type issue with reducers that have actions that expect generic payload

### ISSUE THREAD

**Issue by gdehmlow** [reduxjs/redux-starter-kit#195]
Hi y'all,

I'm currently having an issue creating a slice with generics involved. Here's the representative example:

```ts
export type State<T> = {
  values: T[];
};

export function createGenericSlice<T>({
  name,
}: { name: string }) {
  const initialState: State<T> = { values: [] as T[] };

  const slice = createSlice({
    slice: name,
    initialState,
    reducers: {
      broadcast(state, action: PayloadAction<T>) {
        // do something with action.payload
      }
    }
  });
  const { broadcast } = slice.actions;

  const createObserver = (dispatch) => ({
    onBroadcast(dto) {
      dispatch(broadcast(dto)); // error occurs here
    }
  });
  // Do something with createObserver

  return slice;
}
```

For some reason, using `PayloadAction<T>` causes the type of the `broadcast` action to totally wig out.. I get this error about my `broadcast()` invocation:

`Cannot invoke an expression whose type lacks a call signature. Type 'WithTypeProperty<string, () => WithPayload<undefined, Action<string>>> | WithTypeProperty<string, { (payload?: undefined): WithPayload<undefined, Action<string>>; <PT extends Diff<T, undefined>>(payload?: PT | undefined): WithPayload<PT, Action<string>>; }> | WithTypeProperty<string, <PT extends T>(payload: PT) => WithPayload<PT, Action<string>>>' has no compatible call signatures.`

I'm not _that_ well versed with Typescript to understand the core of the issue here, so maybe this isn't a bug. But if I switch the signature to be, say, `broadcast(state, action: PayloadAction<T[]>)`, I end up with this as the type signature for broadcast: `const broadcast: WithTypeProperty<string, <PT extends T[]>(payload: PT) => WithPayload<PT, Action<string>>>` (which is what I would expect) and I can call `broadcast(dto)` just fine. So the issue specifically has to do with using `PayloadAction<T>`. Is it perhaps because `T` could be undefined (in the case that no generic is passed in)? 

Thank you for your help!

**Comment by markerikson** [comment]
Can you put together a CodeSandbox that demonstrates the issue?

@phryneas , any thoughts?

**Comment by phryneas** [comment]
When I plug this into a codesandbox, I get:

```
Each member of the union type '...' has signatures, but none of those signatures are compatible with each other.
```

And that makes kind of sense if you think about it. The way that `broadcast` can be called can only be determined when the type of Payload is known - and that is only known when `T` finally has a type. The call signatures for all these options are possibly incompatible (with parameter, with optional parameter, without parameter etc.) before T is known.

So, as you already noticed, you can use a Payload with a definitive known signature. Giving it a definitive value like `T[]` or `[T]` would rule out all the unknowns, nulls etc. because array has only one signature.

Alteratively, you can try to narrow T far enough that `PayloadActionCreator<T>` has only one possible signature.

**Comment by markerikson** [comment]
Thanks for the update.

Sounds like there's nothing actionable on our end - it's up to the end user to reasonably constrain the type of the state.
