### ISSUE TITLE
Errors swallowed in createSlice action

### ISSUE THREAD

**Issue by danvoyce** [reduxjs/redux-starter-kit#249]
I've recently noticed that errors seem to be getting swallowed from within the createSlice actions. 

```
export const testSlice = createSlice({
  name: "banners",
  initialState: {
    isSomething: false
  },
  reducers: {
    setIsSomething: (draftState, action) => {
      undefined.fish;
      console.log("Where's my error??");
      draftState.isSomething = action.payload;
    }
  }
});
```

I would have expected an error to have been thrown, but instead nothing after the error is running.

I've created an isolated example where clicking the button calls `dispatch(testSlice.actions.setIsSomething(true))`

 https://codesandbox.io/s/serverless-paper-0n4s2

**Comment by markerikson** [comment]
This is actually [behavior from directly inside `dispatch()` in the Redux core](https://github.com/reduxjs/redux/blob/8aca937f695997e979bf8c0e03dbf22a2bf284dc/src/createStore.js#L202-L207), not anything RSK-specific.

I'll be honest and say I don't know exactly why that was added in the first place (I'd have to dig way back through the source history), but it's been there basically since the beginning.

**Comment by danvoyce** [comment]
This doesn't feel right to me. Do you think I should open a ticket on that repo?

**Comment by markerikson** [comment]
There's actually a good point here:

https://github.com/reduxjs/redux/pull/372#issuecomment-369806261

> if a user's reducer throws an exception, redux's internal state could get locked into `isDispatching === true` which would not be good.

So no, we're not going to change that.
